Feature/frontend/hmi finalizing layout, Finalized HMI Version Without YAAC Notfications
DHBW-SE-2023/YAAC pull request #138
Opened 2024-03-22 18:02 UTC by danielSiegt08

2024-03-23 14:27 UTC, MaxAlberti requested changes
Crashes right after start:
```log
2024/03/23 15:23:33 Info: dial tcp: missing address
2024/03/23 15:23:33 Trying connect to mail server without TLS ...
2024/03/23 15:23:33 Error: dial tcp: missing address
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xba6237]

goroutine 66 [running]:
github.com/DHBW-SE-2023/YAAC/internal/backend/mail.(*BackendMail).setupMail(0x0, 0x1)
        /run/host/home/max/Code/YAAC/internal/backend/mail/mailClient.go:243 +0x17
github.com/DHBW-SE-2023/YAAC/internal/backend/mail.(*BackendMail).GetMailsToday(0x0)
        /run/host/home/max/Code/YAAC/internal/backend/mail/mailClient.go:29 +0x25
github.com/DHBW-SE-2023/YAAC/internal/backend/demon.StartDemon({0xfe3148, 0xc0002d31e0}, 0xa)
        /run/host/home/max/Code/YAAC/internal/backend/demon/demon.go:15 +0x50
created by github.com/DHBW-SE-2023/YAAC/internal/mvvm.(*MVVM).StartDemon in goroutine 1
        /run/host/home/max/Code/YAAC/internal/mvvm/demon.go:12 +0x69
make: *** [Makefile:26: run] Error 2
```
I assume the demon is not initialized correctly/nil.

2024-03-23 14:34 UTC, MaxAlberti requested changes
Please fix

2024-03-23 14:34 UTC, MaxAlberti commented on assets/alive.png
Please bundle all resources!!!

2024-03-23 14:34 UTC, MaxAlberti commented on assets/down.png
Please bundle all resources!!!

2024-03-23 14:34 UTC, MaxAlberti commented on assets/imageIcon.png
Please bundle all resources!!!

2024-03-23 14:34 UTC, MaxAlberti commented on assets/ImageUpload.png
Please bundle all resources!!!

2024-03-23 14:34 UTC, MaxAlberti commented on assets/.DS_Store
Delete this?

2024-03-23 14:37 UTC, MaxAlberti requested changes
Error with script

2024-03-23 14:37 UTC, MaxAlberti commented on dataImport.sh
Error:
```log
↪  ./dataImport.sh                                                                                                Sat Mar 23 15:26:38 CET 2024
Inserting Values
Parse error near line 4: no such column: NULL
  Update Course set DeletedAt=NULL where DeletedAt="NULL";
                                     error here ---^
```

2024-03-23 14:43 UTC, MaxAlberti requested changes
Unprotected settings?

2024-03-23 14:43 UTC, MaxAlberti commented on settings.csv
Encryption? This does not seem compliant. Just temporary?

2024-03-27 23:51 UTC, danielSiegt08 commented on assets/alive.png
All resources got bundled

2024-03-27 23:52 UTC, danielSiegt08 commented on assets/down.png
All resources got bundled

2024-03-27 23:52 UTC, danielSiegt08 commented on assets/imageIcon.png
All resources got bundled

2024-03-27 23:52 UTC, danielSiegt08 commented on assets/ImageUpload.png
All resources got bundled

2024-03-27 23:53 UTC, danielSiegt08 commented on dataImport.sh
The script won't be used in the future since we'll provide a fully configured database.

2024-03-29 18:24 UTC, MaxAlberti approved these changes

2024-03-29 18:28 UTC, merged